const mongoose = require('mongoose');

const userSchema = new mongoose.Schema({
  // Membership Details
  status: String,
  membershipPlan: String,
  numberOfContacts: Number,
  activationDate: String,
  expiryDate: String,

  // User
  prefix: String,
  userId: String,
  name: String,
  phone: String,
  country: String,
  state: String,
  city: String,
  profileCreatedFor: String,
  profilePictureUrls: [String],
  gender: String,
  religion: String,
  caste: String,
  subCaste: String,
  maritalStatus: String,
  dateOfBirth: String,
  age: String,
  email: String,
  password: String,
  referByName: String,
  aboutMe: String,

  // Education Details
  education: String,
  educationDetails: String,
  employedIn: String,
  occupation: String,
  occupationDetails: String,
  annualIncome: String,
  incomeType: String,
  anyOtherSourceIncome: String,
  workingHours: String,
  workingLocationCity: String,
  workingExperience: String,
  workingExperienceDetails: String,

  // Partner Preference
  lookingFor: String,
  partnerAgeRange: String,
  partnerHeightRange: String,
  partnerIncomeRange: String,
  partnerComplexion: String,
  partnerDiet: String,
  expectedEducation: String,
  partnerOccupation: String,
  partnerReligion: String,
  partnerCaste: String,
  partnerSubCaste: String,
  readyToMarryInSameCaste: String,
  partnerCountryLivingIn: String,
  partnerState: String,
  preferredWorkingCities: String,
  preferredNativeCities: String,
  partnerExpectations: String,

  // Family Details
  familyValues: String,
  familyType: String,
  familyStatus: String,
  motherTongue: String,
  numberOfBrothers: String,
  numberOfSisters: String,
  numberOfBrothersMarried: String,
  numberOfSistersMarried: String,
  fatherName: String,
  fatherOccupation: String,
  fatherAlive: String,
  motherName: String,
  motherOccupation: String,
  motherAlive: String,
  parentsStay: String,
  nativeCountry: String,
  nativeState: String,
  nativeDistrict: String,
  nativeCity: String,
  currentCountry: String,
  currentState: String,
  currentDistrict: String,
  currentCity: String,
  mamaName: String,
  mamaCity: String,
  familyWealth: String,
  familyWealthDetails: String,
  surnamesOfRelatives: String,
  aboutFamily: String,
  numberOfChildrenGirl: String,
  numberOfChildrenBoy: String,
  childrenLivingStatus: String,
  // Contact Information
  address: String,
  contactCountry: String,
  contactState: String,
  contactDistrict: String,
  contactCity: String,
  alternatePhone: String,
  mobile: String,
  whatsappNo: String,

  // Basics and Lifestyle
  height: String,
  weight: Number,
  bloodGroup: String,
  complexion: String,
  bodyType: String,
  diet: String,
  anyAchievement: String,
  medicalHistory: String,
  specialCases: String,
  doYouHavePassport: String,
  cardType: String,

  // Horoscope Information
  moonsign: String,
  star: String,
  gotra: String,
  devak: String,
  manglik: String,
  shani: String,
  gan: String,
  nadi: String,
  charan: String,
  horoscopeMatch: String,
  placeOfBirth: String,
  birthCountry: String,
  timeOfBirth: String,

  // Hobbies and Interests
  hobbies: String,
  interests: String,

  isProfileBlur: Boolean,
  isHoroscopeVisible: Boolean,
})

const User = mongoose.model('User', userSchema);

module.exports = User;